spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/citronix
    username: citronix
    password: citronix

  jpa:
    properties:
      hibernate:
        default_schema: public