spring:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/citronix
    username: citronix
    password: citronix

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    change-log: db/changelog/master.yaml
    enabled: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8081


